### PR TITLE
Tools Implementation with new UI changes

### PR DESCRIPTION
**Pull request by niks2060**
Added new functionality for tools and UI changes added new htmlfile in tools to view these changes

### CODE REVIEW

**Comment by niks2060** [comment]
image

**Comment by niks2060** [comment]
@rii-mango @mih @chrisgorgo @inkybutton  Please approve Pull request.

**Comment by niks2060** [comment]
image

**Comment by rii-mango** [comment]
It looks like the changes are:
- adding a Tools list to visually show the modes that are available through keypress combos in original version
- Image Header and Image Description are shown in a sidebar instead of a popup window
- new color choices and adding borders
- reformatting of spaces / tabs / line breaks

**Tools Menu vs Keyboard Reference**
I like the Tools list change- it makes the modes more discoverable than the "Help" -> "Keyboard Reference" interface.

But some of these are tricky and not always appropriate.  Like the "Panning" tool will only work if you have already zoomed in.  And I couldn't get the Invert tools or Cene tool to work.  Maybe they should be grayed out when they don't work?

Also, the keyboard reference options don't seem to work anymore.  They were a nice shortcut for people who already know about them.  Ideally we could use either the keypresses or the Tools menu to start a mode.

Could the "Tool List" be a checkbox item in the "View" menu?

**Image Header & Description Sidebar**
I'm not sure about the sidebar for the Image Header and Image Description.  It make sense for larger screens, and there are a lot of larger screens these days, but some uses of Papaya are more compact, [like this](http://brainmap.org/taxonomy/behaviors/Cognition.All.html).

Could it be optional, based on the html file?  I couldn't get the debug_local.html to load anymore after switching to this Tools branch.

Also, could the "Show Image Description" button on the left side fit into one of the Tools and/or in the View menu?  I agree it was not a great fit inside the menu it was inside previously, but I'm not sure it makes sense to have an always displayed button along the side either.

**Colors and Borders**
The new colors and borders are nice.  We should be careful with colorblindness and not distinguish only with color.  These changes are adding to what was there, so I'm okay accepting them.

**Reformatting**
Please minimize reformatting while making other changes.  It's harder to review the functional changes while reformatting changes are showing in the diff.

**Menu bug**
The menu items are displaying too high, and covering up the Menu itself.  So now it's much harder to dismiss the File menu after clicking on it.

**Comment by niks2060** [comment]
@rii-mango For tools all other stuff in not required. It is optional when we send param["imageTools"] = true. Also I am working on cene tool and slider also. They will be available in next PR.

**Comment by niks2060** [comment]
Tools Menu vs Keyboard Reference
I like the Tools list change- it makes the modes more discoverable than the "Help" -> "Keyboard Reference" interface.


But some of these are tricky and not always appropriate. Like the "Panning" tool will only work if you have already zoomed in. And I couldn't get the Invert tools or Cene tool to work. Maybe they should be grayed out when they don't work?
-- I had same concern but as Zoom also needs to be centralize and canvas size is same as image it wont allow PAN.

Also, the keyboard reference options don't seem to work anymore. They were a nice shortcut for people who already know about them. Ideally we could use either the keypresses or the Tools menu to start a mode.

-- I think it working as expected after testing.

Could the "Tool List" be a checkbox item in the "View" menu?

-- Do this is required as I have made this optional as params["imageTools"] needs to set as true. If required let me know will implement that way.

Image Header & Description Sidebar
I'm not sure about the sidebar for the Image Header and Image Description. It make sense for larger screens, and there are a lot of larger screens these days, but some uses of Papaya are more compact, [like this](http://brainmap.org/taxonomy/behaviors/Cognition.All.html).

-- This is optional but most of the people needed this but I will remove this in next change as I am focused on Overlay than a description.

Could it be optional, based on the html file? I couldn't get the debug_local.html to load anymore after switching to this Tools branch.

-- I have resolved these issues as I have defined viewerTools reference at the top of viewer initialization because of which it was failing. 

Also, could the "Show Image Description" button on the left side fit into one of the Tools and/or in the View menu? I agree it was not a great fit inside the menu it was inside previously, but I'm not sure it makes sense to have an always displayed button along the side either.

--- Will remove that I intended to implement overlays this is HTML page specific when    params["imageTools"] is set to true but will move this to menu item or remove it for time being as will change all header part as overlays.

Colors and Borders
The new colors and borders are nice. We should be careful with colorblindness and not distinguish only with color. These changes are adding to what was there, so I'm okay accepting them.


-- Thanks, I have thought this this way that the RGBY
 pattern where R -Axial, G-Coronal and B-Sagittal and Y-Surface 

Reformatting
Please minimize reformatting while making other changes. It's harder to review the functional changes while reformatting changes are showing in the diff.


-- I had very bad habit of formatting code when working. I will try to minimize the formatting. 

Menu bug
The menu items are displaying too high, and covering up the Menu itself. So now it's much harder to dismiss the File menu after clicking on it.

-- Resolved this by adding new variable.

**Comment by niks2060** [comment]
After update

image

Also verified with debug_local.html

image

**Comment by niks2060** [comment]
I am waiting for completion of this pull request as I have done with Play Cine and Overlays and Working on Ruler drawing on each screenSlice. 

image

**Pull request merged**
