### PR TITLE
enable parallel loading of images

### PR DESCRIPTION
**Pull request by marlocorridor**
for #53

### CODE REVIEW

**Comment by rii-mango** [comment]
Looks good!  Just wanted to let you know it may take a couple of weeks to get this merged in, but it will eventually.  Thanks.

**Comment by marlocorridor** [comment]
Glad to contribute on this project. :)

**Comment by marlocorridor** [comment]
**off topic**
Could you explain why this is not for clinical use? Thanks. :)

**Comment by rii-mango** [comment]
I think normally to be used in a clinical setting, software needs FDA approval.  We say "Not for clinical use" just as a reminder to people that this software is more geared for research purposes and does not have clinical certification.

**Pull request merged**
